apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "servicebeard.fullname" . }}-api
  labels:
    {{- include "servicebeard.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "servicebeard.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "servicebeard.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}-api:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.port }}
          envFrom:
            - configMapRef:
                name: {{ include "servicebeard.fullname" . }}-config
            - secretRef:
                name: {{ include "servicebeard.fullname" . }}-secrets
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.api.port }}
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.api.port }}
            initialDelaySeconds: 5
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
