{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "servicebeard.fullname" . }}-migrate
  labels:
    {{- include "servicebeard.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}-api:{{ .Values.image.tag }}"
          command: ["bun", "run", "db:migrate"]
          workingDir: /app
          envFrom:
            - secretRef:
                name: {{ include "servicebeard.fullname" . }}-secrets
{{- end }}
