{{- if .Values.postgresql.enabled }}
{{- $dbUrl := printf "postgres://%s:%s@%s-postgresql:5432/%s?sslmode=disable" .Values.postgresql.auth.username .Values.postgresql.auth.password .Release.Name .Values.postgresql.auth.database }}
{{- else }}
{{- $dbUrl := .Values.externalDatabase.url }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "servicebeard.fullname" . }}-secrets
  labels:
    {{- include "servicebeard.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ if .Values.postgresql.enabled }}{{ printf "postgres://%s:%s@%s-postgresql:5432/%s?sslmode=disable" .Values.postgresql.auth.username .Values.postgresql.auth.password .Release.Name .Values.postgresql.auth.database }}{{ else }}{{ .Values.externalDatabase.url }}{{ end }}
  OIDC_CLIENT_SECRET: {{ .Values.secrets.oidcClientSecret | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.secrets.githubClientSecret | quote }}
  GITLAB_CLIENT_SECRET: {{ .Values.secrets.gitlabClientSecret | quote }}
  SESSION_SECRET: {{ .Values.secrets.sessionSecret | quote }}
  ENCRYPTION_KEY: {{ .Values.secrets.encryptionKey | quote }}
