# syntax=docker/dockerfile:1.4
# Bun >= 1.3.11 required: older versions crash in node:tls checkServerIdentity
# during STARTTLS handshakes (getPeerCertificate returned undefined).
# See https://github.com/oven-sh/bun/issues/24374
FROM oven/bun:1.3-alpine AS base
WORKDIR /app

# ── OSS dependencies ──
FROM base AS deps
COPY package.json bun.lock ./
COPY apps/api/package.json ./apps/api/
COPY apps/worker/package.json ./apps/worker/
COPY apps/web/package.json ./apps/web/
COPY packages/db/package.json ./packages/db/
COPY packages/mail/package.json ./packages/mail/
COPY packages/providers/package.json ./packages/providers/
COPY packages/shared/package.json ./packages/shared/
# Force hoisted node_modules: the build stages below copy only the root
# /app/node_modules between stages, which requires a flat (hoisted) layout.
# Bun 1.3 defaults workspaces to the isolated linker, which breaks that.
RUN bun install --linker hoisted --frozen-lockfile || bun install --linker hoisted

# ── Extension sources (optional named build context: extension) ──
FROM base AS extension-context
COPY --from=extension . /extension

FROM base AS extension-deps
COPY --from=extension-context /extension /extension
# Cloud extensions link OSS packages via file:../serviceboard/packages/* (sibling checkout).
COPY packages/db /serviceboard/packages/db
COPY packages/mail /serviceboard/packages/mail
COPY packages/shared /serviceboard/packages/shared
COPY packages/providers /serviceboard/packages/providers
WORKDIR /extension
RUN if [ -f package.json ]; then bun install --linker hoisted --frozen-lockfile || bun install --linker hoisted; else mkdir -p node_modules; fi

# ── Web build (bundles extension UI when manifest is present) ──
FROM base AS web-build
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# Vite reads envPrefix vars from monorepo .env (generated by deploy/compose/extract-vite-env.ts).
RUN if [ -f deploy/compose/.env.vite ]; then \
      cp deploy/compose/.env.vite /app/.env; \
    else \
      cp deploy/compose/.env.vite.example /app/.env; \
    fi
COPY --from=extension-context /extension /extension
COPY --from=extension-deps /extension/node_modules /extension/node_modules
WORKDIR /app/apps/web
RUN SB_EXTENSION_MANIFEST=; \
    if [ -f /extension/extension.config.ts ]; then SB_EXTENSION_MANIFEST=/extension/extension.config.ts; \
    elif [ -f /extension/extension.config.js ]; then SB_EXTENSION_MANIFEST=/extension/extension.config.js; fi; \
    if [ -n "$SB_EXTENSION_MANIFEST" ]; then \
      (cd /app && SB_EXTENSION_MANIFEST="$SB_EXTENSION_MANIFEST" bun run scripts/copy-extension-public.ts /app/apps/web/public); \
    fi; \
    export SB_EXTENSION_MANIFEST; \
    bunx vite build

# ── API image ──
FROM base AS api
COPY --from=deps /app/node_modules ./node_modules
COPY . .
COPY --from=extension-context /extension /extension
COPY --from=extension-deps /extension/node_modules /extension/node_modules
COPY packages/db /serviceboard/packages/db
COPY packages/mail /serviceboard/packages/mail
COPY packages/shared /serviceboard/packages/shared
COPY packages/providers /serviceboard/packages/providers
RUN if [ -f /extension/package.json ]; then \
      ln -sfn /app/node_modules /serviceboard/node_modules && \
      mkdir -p /extension/node_modules/@servicebeard && \
      for pkg in api db mail providers shared; do \
        ln -sfn "/app/node_modules/@servicebeard/${pkg}" "/extension/node_modules/@servicebeard/${pkg}"; \
      done; \
    fi
WORKDIR /app/apps/api
EXPOSE 3000
CMD ["sh", "-c", "if [ -f /extension/extension.config.ts ]; then export SB_EXTENSION_MANIFEST=/extension/extension.config.ts; elif [ -f /extension/extension.config.js ]; then export SB_EXTENSION_MANIFEST=/extension/extension.config.js; fi && cd /app && bun run db:migrate && cd /app/apps/api && bun run start"]

# ── Worker image ──
FROM base AS worker
COPY --from=deps /app/node_modules ./node_modules
COPY . .
COPY --from=extension-context /extension /extension
COPY --from=extension-deps /extension/node_modules /extension/node_modules
COPY packages/db /serviceboard/packages/db
COPY packages/mail /serviceboard/packages/mail
COPY packages/shared /serviceboard/packages/shared
COPY packages/providers /serviceboard/packages/providers
RUN if [ -f /extension/package.json ]; then \
      ln -sfn /app/node_modules /serviceboard/node_modules && \
      mkdir -p /extension/node_modules/@servicebeard && \
      for pkg in api db mail providers shared; do \
        ln -sfn "/app/node_modules/@servicebeard/${pkg}" "/extension/node_modules/@servicebeard/${pkg}"; \
      done; \
    fi
WORKDIR /app/apps/worker
CMD ["sh", "-c", "if [ -f /extension/extension.config.ts ]; then export SB_EXTENSION_MANIFEST=/extension/extension.config.ts; elif [ -f /extension/extension.config.js ]; then export SB_EXTENSION_MANIFEST=/extension/extension.config.js; fi && bun run start"]

# ── Web image ──
FROM nginx:alpine AS web
COPY --from=web-build /app/apps/web/dist /usr/share/nginx/html
COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
